/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package college.AdminFolder;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibrahim
 */
public class category_page extends javax.swing.JFrame {

    /**
     * Creates new form category_page
     */
    public category_page() {
        initComponents();
        viewActionPerformed(null);
        view.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Ensure only this window is closed

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        categorytable = new javax.swing.JTable();
        addcategory = new javax.swing.JButton();
        view = new javax.swing.JButton();
        hoempage = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categorytable.setBackground(new java.awt.Color(153, 255, 255));
        categorytable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categorytable.setForeground(new java.awt.Color(0, 51, 51));
        categorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "title", "quantity"
            }
        ));
        jScrollPane1.setViewportView(categorytable);

        addcategory.setBackground(new java.awt.Color(153, 255, 255));
        addcategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addcategory.setForeground(new java.awt.Color(0, 51, 51));
        addcategory.setText("Add Category");
        addcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcategoryActionPerformed(evt);
            }
        });

        view.setBackground(new java.awt.Color(153, 255, 255));
        view.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        view.setForeground(new java.awt.Color(0, 51, 51));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        hoempage.setBackground(new java.awt.Color(153, 255, 255));
        hoempage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hoempage.setForeground(new java.awt.Color(0, 51, 51));
        hoempage.setText("go back home");
        hoempage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoempageActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(153, 255, 255));
        delete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 51, 51));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(153, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hoempage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(addcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoempage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTextField1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcategoryActionPerformed
         // Create instance of add_category and pass the reference
    add_category cat = new add_category(this); // Assuming 'this' is an instance of category_page
    cat.setLocationRelativeTo(this);
    cat.setVisible(true);

    // Add a WindowListener to handle when the add_category window is closed
    cat.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent evt) {
            // Call the viewActionPerformed method of the category_page
            viewActionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "view"));
        }
    });

        

    }//GEN-LAST:event_addcategoryActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
                 Connection connect = null;
		Statement s = null;
		Boolean status = false;
        try {  
            Class.forName("com.mysql.jdbc.Driver");
            String myUrl = "jdbc:mysql://localhost:3305/universityproject";
            connect = DriverManager.getConnection(myUrl, "root", "");
            s = connect.createStatement();

        String query = "SELECT * FROM category;";
        ResultSet rs = s.executeQuery(query);

        // Clear table before populating
        DefaultTableModel model = (DefaultTableModel) categorytable.getModel();
        model.setRowCount(0); // Clearing the existing rows

        // Populating table from ResultSet
        while (rs.next()) {
            String id = rs.getString("category_id");
            String title = rs.getString("category_title");
            String quantity = rs.getString("category_quantity");


            model.addRow(new Object[] { id, title, quantity  });
        } 
        rs.close();
        connect.close();
    } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, "Could Not add");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error In Connectivity");
        }
    }//GEN-LAST:event_viewActionPerformed

    private void hoempageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoempageActionPerformed

        this.dispose();
    }//GEN-LAST:event_hoempageActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
                Connection connect = null;
		Statement s = null;
		Boolean status = false;
        try {  
            Class.forName("com.mysql.jdbc.Driver");
            String myUrl = "jdbc:mysql://localhost:3305/universityproject";
            connect = DriverManager.getConnection(myUrl, "root", "");
            s = connect.createStatement();

        // Check if the roll number exists
        String rollNumber = jTextField1.getText();
        String checkQuery = "SELECT * FROM category WHERE category_id = ?";
        PreparedStatement checkStmt = connect.prepareStatement(checkQuery);
        checkStmt.setString(1, rollNumber);
        ResultSet rs = checkStmt.executeQuery();
        
        if (rs.next()) {
            // Roll number found, proceed with delete
            String deleteQuery = "DELETE FROM category WHERE category_id = ?";
            PreparedStatement deleteStmt = connect.prepareStatement(deleteQuery);
            deleteStmt.setString(1, rollNumber);
            deleteStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record deleted successfully.");
            jTextField1.setText("");
            deleteStmt.close();
            viewActionPerformed(evt);

        } else {
            // Roll number not found
            JOptionPane.showMessageDialog(null, "Cannot delete category, category number does not exist.");
        }
        
        // Close the ResultSet, PreparedStatement, and Connection
        rs.close();
        checkStmt.close();
        connect.close();  
    } catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    } 
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(category_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(category_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(category_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(category_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new category_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcategory;
    private javax.swing.JTable categorytable;
    private javax.swing.JButton delete;
    private javax.swing.JButton hoempage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
