/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package college.AdminFolder;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibrahim
 */
public class product_page extends javax.swing.JFrame {

    /**
     * Creates new form product_page
     */
    public product_page() {
        initComponents();
        viewActionPerformed(null);
        view.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Ensure only this window is closed

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addproduct = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        productstable = new javax.swing.JTable();
        view = new java.awt.Button();
        homepage = new java.awt.Button();
        delete = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addproduct.setBackground(new java.awt.Color(153, 255, 255));
        addproduct.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addproduct.setForeground(new java.awt.Color(0, 51, 51));
        addproduct.setLabel("Add Product");
        addproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductActionPerformed(evt);
            }
        });

        productstable.setBackground(new java.awt.Color(153, 255, 255));
        productstable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productstable.setForeground(new java.awt.Color(0, 51, 51));
        productstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "title", "descritption", "stock", "keywords", "category", "image 1", "image 2", "image 3", "price"
            }
        ));
        jScrollPane2.setViewportView(productstable);

        view.setBackground(new java.awt.Color(153, 255, 255));
        view.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        view.setForeground(new java.awt.Color(0, 51, 51));
        view.setLabel("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        homepage.setBackground(new java.awt.Color(153, 255, 255));
        homepage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        homepage.setForeground(new java.awt.Color(0, 51, 51));
        homepage.setLabel("return to home");
        homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(153, 255, 255));
        delete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 51, 51));
        delete.setLabel("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(153, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
    try {
    // Establish connection  
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universityproject", "root", "");  
    Statement statement = con.createStatement(); 
    
    // Step 1: Retrieve product data
    String productQuery = "SELECT * FROM product;";
    ResultSet productRs = statement.executeQuery(productQuery);
    
    // Clear table before populating
    DefaultTableModel model = (DefaultTableModel) productstable.getModel();
    model.setRowCount(0); // Clearing the existing rows
    
    // Step 2: Process each product and retrieve category name
    while (productRs.next()) {
        String id = productRs.getString("product_id");
        String title = productRs.getString("product_title");
        String description = productRs.getString("product_description");
        String stock = productRs.getString("product_stock");
        String keyword = productRs.getString("product_keyword");
        String categoryId = productRs.getString("category_id");
        String image1 = productRs.getString("product_image1");
        String image2 = productRs.getString("product_image2");
        String image3 = productRs.getString("product_image3");
        String price = productRs.getString("product_price");
        
        // Step 2.1: Retrieve category name based on category_id
        String category = "";
        String categoryQuery = "SELECT category_title FROM category WHERE category_id = ?";
        PreparedStatement categoryStmt = con.prepareStatement(categoryQuery);
        categoryStmt.setString(1, categoryId);
        ResultSet categoryRs = categoryStmt.executeQuery();
        
        if (categoryRs.next()) {
            category = categoryRs.getString("category_title");
        }
        
        // Close the ResultSet and PreparedStatement for category
        categoryRs.close();
        categoryStmt.close();
        
        // Add row to the table model
        model.addRow(new Object[] { id, title, description, stock, keyword, category, image1, image2, image3, price });
    } 
    
    // Close the ResultSet and Statement for products
    productRs.close();
    statement.close();
    con.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Could Not add");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error In Connectivity");
}

    }//GEN-LAST:event_viewActionPerformed

    private void addproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductActionPerformed
        
        add_product new_product = new add_product();
        new_product.setLocationRelativeTo(this);
        new_product.setVisible(true);
    }//GEN-LAST:event_addproductActionPerformed

    private void homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageActionPerformed
      
       this.dispose();
    }//GEN-LAST:event_homepageActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
            
        try {  
        Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universityproject", "root", "");  

        // Check if the roll number exists
        String rollNumber = jTextField1.getText();
        String checkQuery = "SELECT * FROM product WHERE product_id = ?";
        PreparedStatement checkStmt = con.prepareStatement(checkQuery);
        checkStmt.setString(1, rollNumber);
        ResultSet rs = checkStmt.executeQuery();
        
        if (rs.next()) {
            // Roll number found, proceed with delete
            String deleteQuery = "DELETE FROM product WHERE product_id = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deleteQuery);
            deleteStmt.setString(1, rollNumber);
            deleteStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record deleted successfully.");
            jTextField1.setText("");
            deleteStmt.close();
            viewActionPerformed(null);
        } else {
            // Roll number not found
            JOptionPane.showMessageDialog(null, "Cannot delete product, product number does not exist.");
        }
        
        // Close the ResultSet, PreparedStatement, and Connection
        rs.close();
        checkStmt.close();
        con.close();  
    } catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    } 
        
    }//GEN-LAST:event_deleteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addproduct;
    private java.awt.Button delete;
    private java.awt.Button homepage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable productstable;
    private java.awt.Button view;
    // End of variables declaration//GEN-END:variables
}
